name: Validate Agent YAML

on:
  pull_request:
    paths:
      - '.claude/agents/*.md'
      - 'tests/validate_yaml.sh'
  push:
    branches:
      - main
      - master
    paths:
      - '.claude/agents/*.md'
      - 'tests/validate_yaml.sh'

jobs:
  validate-yaml:
    name: Validate YAML Front-Matter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Make validation script executable
        run: chmod +x tests/validate_yaml.sh
        
      - name: Run YAML validation
        run: |
          cd tests
          ./validate_yaml.sh
          
      - name: Run validation unit tests
        if: always()
        run: |
          cd tests
          if [ -f "./test_yaml_validation.sh" ]; then
            chmod +x ./test_yaml_validation.sh
            ./test_yaml_validation.sh
          fi